Gemfile
app/controllers/cart_items_controller.rb
app/views/cart_items/index.html.erb
app/views/products/index.html.erb
app/views/products/show.html.erb

カート機能
controller&views記述
contollerの方は自信がないので後々修正すると思います
viewの方は一応、税込み価格の算出、数量×単価、合計金額を反映。三桁目でカンマを入れるようにしています。

Cart items

---

app/controllers/application_controller.rb
app/controllers/homes_controller.rb
app/controllers/members_controller.rb
app/controllers/products_controller.rb
app/models/member.rb
app/models/product.rb
app/views/layouts/application.html.erb
app/views/members/registrations/new.html.erb
app/views/members/show.html.erb
config/routes.rb
db/migrate/20200516024130_devise_create_members.rb

[add]mypage

---

app/controllers/members_controller.rb
app/views/members/hide.html.erb
config/routes.rb
db/migrate/20200516024130_devise_create_members.rb

[add]hidepage&action

---

db/migrate/20200516030438_create_orders.rb
db/schema.rb

#マイグレーションファイルを編集しました。
* null false を追加しました。
* postage・pay_method・order_status のそれぞれにdefault値を追加しました。

add null false & default

---

app/controllers/admins/genres_controller.rb
app/controllers/admins/products_controller.rb
app/controllers/members_controller.rb
app/views/admins/genres/index.html.erb
app/views/admins/products/new.html.erb
app/views/admins/products/show.html.erb
app/views/members/edit.html.erb
app/views/members/registrations/new.html.erb
config/routes.rb
db/migrate/20200516024130_devise_create_members.rb
db/schema.rb

会員情報編集ページ追加
コントローラにedit,updateアクション追加

[add]member_editaction&page

---

app/controllers/cart_items_controller.rb
db/schema.rb

カート機能
コントローラのindexアクション間違っていたので修正してます

[edit]cart_itemscontroller

---

app/controllers/products_controller.rb
app/views/cart_items/index.html.erb
app/views/layouts/application.html.erb
app/views/members/show.html.erb
app/views/products/index.html.erb
app/views/products/show.html.erb

カート機能
・商品一つずつ削除の動作
・買い物を続ける場合は商品一覧へパス
商品機能
・商品一覧→商品詳細へのパス
・ジャンル検索：とりあえずジャンル名表示
マイページ
・会員情報編集ページへのパス
ヘッダー
・カートと商品一覧ページへのパス
上記の更新と動作確認済

[add]productsindex-genre search

---

app/controllers/admins/homes_controller.rb
app/views/admins/genres/edit.html.erb
app/views/admins/genres/index.html.erb
app/views/admins/members/edit.html.erb
app/views/admins/members/index.html.erb
app/views/admins/members/show.html.erb
app/views/admins/products/index.html.erb
app/views/admins/products/new.html.erb
config/routes.rb

admin側の商品、会員、ジャンルビューをbootstrap仕様に変更
各種リンク追加

ビューリンク変更追加

---

app/controllers/members/sessions_controller.rb
app/controllers/members_controller.rb
app/models/member.rb
app/views/members/edit.html.erb
app/views/members/quit.html.erb
app/views/members/show.html.erb
config/routes.rb

[modified]quitpage&hideaction

---

app/controllers/application_controller.rb
app/controllers/cart_items_controller.rb
app/controllers/members_controller.rb
app/views/cart_items/index.html.erb
app/views/products/index.html.erb
app/views/products/show.html.erb
db/seeds.rb

・カート機能
数量を１以上の数値しか入力できないように変更
金額の表示：小数点以下を非表示
・商品機能
金額の表示：小数点以下を非表示
・会員機能
カラム名のスペルミスを変更
・seeds.rbファイル
商品登録を自分でいちいちするのが面倒だったので初期でデータ作成しました
商品とジャンルを複数作ってます
不要だったら消してもらっても大丈夫です

[modified]cart_itempage&productspage

---

app/controllers/admins/genres_controller.rb
app/controllers/admins/members_controller.rb
app/controllers/admins/products_controller.rb
app/controllers/application_controller.rb

adminがログイン時のみにしかビューを見れなくしました。
adminの新規登録も出来るので、みなさん確認出来ます。

[adminログイン規制]

---

app/views/members/show.html.erb
app/views/products/index.html.erb
config/routes.rb

・会員機能
会員詳細ページにパスワード再設定ページのパス追加

[modified]member-password-edit-path

---

app/views/cart_items/index.html.erb
app/views/products/index.html.erb
app/views/products/show.html.erb
db/seeds.rb

・ジャンル検索
商品詳細ページでもジャンル検索ができるように修正
bootstrapで使用できるようにテーブルタグ記述

[modified]productviews:genre search

---

app/controllers/admins/orders_controller.rb
app/models/genre.rb
app/models/member.rb
app/models/product.rb
app/views/admins/members/show.html.erb

admin
ジャンル、会員、商品に関するバリデーションを追加しました。

[validate追加]

---

app/views/orders/index.html.erb
app/views/orders/show.html.erb

会員側：注文機能
・注文履歴一覧
・注文履歴詳細
上記のviewを作成
コントローラ側の変数の書き方などによっては変更になる可能性有

[add]view:order-index&show

---

app/controllers/cart_items_controller.rb
app/controllers/products_controller.rb
app/views/cart_items/index.html.erb
app/views/layouts/application.html.erb
app/views/products/index.html.erb

商品機能
・ジャンル検索の際に(ジャンル名)一覧になるように変更
ヘッダー
・マイページのパス記述
カート機能
・商品追加、削除、カートを空にする、数量変更ごとにメッセージの表示ができるように変更
すべて動作確認済み

[modified]search-title

---

app/controllers/products_controller.rb
app/views/products/index.html.erb

[modifed]products-pagination

---

app/models/order_item.rb
db/migrate/20200516030807_create_order_items.rb

注文商品
・モデルにリレーション追加
・enum追加：間違ってるかもしれません

[add]model:order_item

---

app/controllers/members/sessions_controller.rb
app/views/members/sessions/new.html.erb
db/schema.rb

退会機能
・動作確認後、不具合調整
・退会済みのユーザーがログインした場合のメッセージ表記、パスの修正

[modified]quit message

---

app/models/address.rb
app/models/member.rb
app/views/address/index.html.erb
app/views/members/show.html.erb

・バリデーション
address.rbにもmember.rb同様にバリデーション追加
※ハイフン入力できないなど
・会員機能
会員詳細画面：注文履歴へのパスを記述

[modified]views:member-show&address:validation

---

app/views/members/registrations/edit.html.erb

[modified]edit-registrations

---

app/controllers/members/sessions_controller.rb

[sign_inでエラー]

---

app/controllers/cart_items_controller.rb
app/controllers/members/sessions_controller.rb
app/views/products/show.html.erb

[modified]views:product-show

---

app/controllers/admins/genres_controller.rb
app/models/genre.rb
app/models/home.rb
app/models/product.rb
app/views/admins/genres/edit.html.erb
config/routes.rb

adminで起きてたエラーを改善しました。
恐らくコンフリクト起きます。

[pullによるeroorの改善]

---

app/controllers/members/sessions_controller.rb

[modified]session-controller

---

app/controllers/admins/orders_controller.rb
app/views/admins/genres/index.html.erb
app/views/admins/members/index.html.erb
app/views/admins/orders/index.html.erb
app/views/admins/products/index.html.erb
app/views/admins/products/show.html.erb

レイアウトを整えました。
３桁以上の数字にはカンマ、税込みの計算表示出来てない所があったので修正入れました。
注文詳細少々書き進めてます。

[レイアウト、機能追加]

---

app/views/layouts/application.html.erb
app/views/members/sessions/new.html.erb

検索ボックス　パスワードを忘れたときのpath

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/stylesheets/application.scss

gemfileにbootstrap追加
application.js,application.scssなどに必要事項記入

[add]install-bootstrap

---

app/views/address/edit.html.erb
app/views/address/index.html.erb
app/views/admins/sessions/new.html.erb
app/views/members/registrations/new.html.erb
app/views/members/sessions/new.html.erb

申し訳ありませんブートストラップのclassの書き方に間違いがあったので修正しました

ブートストラップ対応修正

---

app/views/cart_items/index.html.erb
app/views/products/index.html.erb
app/views/products/show.html.erb

・商品機能
bootstrap対応のレイアウトに変更
・カート機能
レイアウトまだ途中

[modified]product-layouts

---

app/controllers/admins/orders_controller.rb
app/models/order.rb
app/views/admins/orders/index.html.erb
app/views/admins/orders/show.html.erb

orderのindexページ、showページ（上半分）作成。
コントローラも記述を追加

[view_controller]

---

app/controllers/admins/order_items_controller.rb
app/controllers/admins/orders_controller.rb
app/views/admins/orders/show.html.erb
config/routes.rb

・会員側：注文詳細機能
admins/orders/show.html.erb
26行目<tbody>~以下を作成。
→表示確認しました。特に自分の環境ではエラーが発生しませんでした。
※表示確認のためにadmin::order.controllerも記述したのでコンフリクト発生の可能性あり。
order_items.controller記述
→製作ステータスが保存されるようにしました。ルーティングも追記しています。
ターミナルでrollback transactionが起こらないか確認済み。データ保存されているか確認済み。

[add]making_status

---

app/assets/stylesheets/cart_items.scss
app/views/cart_items/index.html.erb
app/views/products/show.html.erb

[modified]layouts-cart

---

app/assets/stylesheets/orders.scss
app/controllers/orders_controller.rb
app/views/orders/index.html.erb
app/views/orders/new.html.erb
app/views/orders/order_show.html.erb
app/views/orders/show.html.erb
app/views/orders/success.html.erb
config/application.rb

* 注文日の表示を「年/月/日 時間:分」に変更しました。
* レイアウトを若干調整しました。

Fix & Update

---

app/views/orders/_order_status.html.erb
app/views/orders/_pay_method.html.erb
app/views/orders/show.html.erb

* 支払い方法の表示を調整しました。
* 注文履歴詳細ページにlinkボタンを追加しました。

Update order view

---

app/assets/stylesheets/members.scss
app/views/cart_items/index.html.erb
app/views/members/edit.html.erb
app/views/members/quit.html.erb
app/views/members/registrations/edit.html.erb
app/views/members/show.html.erb

[modified]layouts-member

---

app/views/admins/genres/index.html.erb
app/views/admins/homes/top.html.erb
app/views/admins/members/edit.html.erb
app/views/admins/members/show.html.erb
app/views/admins/orders/index.html.erb
app/views/admins/orders/show.html.erb
app/views/admins/products/edit.html.erb
app/views/admins/products/index.html.erb
app/views/admins/products/new.html.erb
app/views/admins/products/show.html.erb

ログイン画面で注文カウントから当該リンクに飛べます
各種ビューを変更しました。
その他リンクの追記、turbolinkを避ける書き方に変更しました。

[adminビュー、リンク]

---

app/assets/stylesheets/homes.scss
app/controllers/homes_controller.rb
app/views/homes/top.html.erb

[modified]lyaouts-top-search

---

app/controllers/products_controller.rb
app/views/address/index.html.erb
app/views/members/registrations/new.html.erb
app/views/members/sessions/new.html.erb

商品機能
・表示件数変更
会員機能
・ログイン、新規登録画面などのレイアウトを変更

[modified]layotus-login

---

app/views/address/edit.html.erb
app/views/admins/homes/top.html.erb
app/views/admins/orders/show.html.erb
app/views/admins/sessions/new.html.erb

adminの配送先を正しく変更
adminの注文履歴詳細を正しく書き換え
memberの配送先編集をターボリンク効いていたので外した。

admin-order-fix

---

app/controllers/admins/products_controller.rb
app/views/admins/genres/index.html.erb
app/views/admins/products/new.html.erb

[admin_test]

---

app/controllers/orders_controller.rb
app/views/orders/new.html.erb

add error message

---

app/views/address/index.html.erb
app/views/members/edit.html.erb

form_forの編集

---

Gemfile
Gemfile.lock
app/controllers/admins/order_items_controller.rb
app/views/admins/orders/show.html.erb
spec/factories/members.rb
spec/factories/products.rb
spec/rails_helper.rb
spec/requests/cart_items_request_spec.rb
spec/requests/members_request_spec.rb
spec/requests/products_request_spec.rb
spec/spec_helper.rb

[modified]status-auto
